name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-kpimg:
    runs-on:  ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Install Compiler
        run: |
          curl -o arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
          tar -Jxf arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
      - name: Build
        run: |
          export TARGET_COMPILE=`pwd`/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-
          cd kernel
          make
      - name: Upload kpimg
        uses: actions/upload-artifact@v3
        with:
          path: |
            kernel/kpimg
          name: kpimg
      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          body: "..."
          artifacts: "kernel/kpimg"
          allowUpdates: true
          replacesArtifacts: true

  upload-libs:
    permissions:
      contents: write
    runs-on:  ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Zip-lib
        run: |
          export TARGET_COMPILE="placeholder"
          cd kernel
          make hdr
          cd ..
          zip -r kptools.zip tools
          zip -r kpuser.zip user
      - name: Release-kptools
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          body: ""
          artifacts: "kptools.zip"
          allowUpdates: true
          replacesArtifacts: true
      - name: Release-kpuser
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          body: ""
          artifacts: "kpuser.zip"
          allowUpdates: true
          replacesArtifacts: true
          
#   build-kptools-linux:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out
#         uses: actions/checkout@v3
#         with:
#           submodules: "recursive"
#           fetch-depth: 0
#       - name: Build
#         run: |
#           cd tools
#           make
#           mv kptools kptools-linux
#       - name: Upload artifact
#         uses: actions/upload-artifact@v3
#         with:
#           path: tools/kptools-linux
#           name: kptools-linux
#       - name: Release
#         uses: ncipollo/release-action@v1.12.0
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           tag: latest
#           body: "..."
#           artifacts: "tools/kptools-linux"
#           allowUpdates: true
#           replacesArtifacts: true
          
#   build-kptools-mac:
#     permissions:
#       contents: write
#     runs-on: macos-latest
#     steps:
#       - name: Check out
#         uses: actions/checkout@v3
#         with:
#           submodules: "recursive"
#           fetch-depth: 0
#       - name: Build
#         run: |
#           cd tools
#           make
#           mv kptools kptools-mac
#       - name: Upload artifact
#         uses: actions/upload-artifact@v3
#         with:
#           path: tools/kptools-mac
#           name: kptools-mac
#       - name: Release
#         uses: ncipollo/release-action@v1.12.0
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           tag: latest
#           body: "..."
#           artifacts: "tools/kptools-mac"
#           allowUpdates: true
#           replacesArtifacts: true
          

